data:extend({
        {
            type = "bool-setting",
            name = "geothermal-uses-tungsten",
            setting_type = "startup",
            default_value = true,
            order = "r",
		},
        {
            type = "double-setting",
            name = "geothermal-power-factor",
            setting_type = "startup",
            default_value = 1,
            order = "r",
			minimum_value = 0.5,
			maximum_value = 10,
		},
        {
            type = "double-setting",
            name = "geothermal-frequency",
            setting_type = "startup",
            default_value = 1,
            order = "r",
			minimum_value = 0.25,
			maximum_value = 4,
		},
        {
            type = "double-setting",
            name = "geothermal-size",
            setting_type = "startup",
            default_value = 1,
            order = "r",
			minimum_value = 0.33,
			maximum_value = 6,
		},
        {
            type = "bool-setting",
            name = "geothermal-color",
            setting_type = "startup",
            default_value = true,
            order = "r",
		},
        {
            type = "string-setting",
            name = "geothermal-spawn-rules",
            setting_type = "startup",
            default_value = "volcanic",
			allowed_values = {"volcanic", "volcanic-and-snow", "volcanic-snow-and-red-desert", "everywhere"},
            order = "r",
		},
        {
            type = "double-setting",
            name = "geothermal-distance-scalar",
            setting_type = "startup",
            default_value = 1,
            order = "r",
			minimum_value = 0.1,
			maximum_value = 10,
		},
        {
            type = "double-setting",
            name = "geothermal-min-distance",
            setting_type = "startup",
            default_value = 300,
            order = "r",
			minimum_value = 0,
			maximum_value = 6000,
		},
})
